{% set name = "folium" %}
{% set version = "0.12.1.post1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/folium-{{ version }}.tar.gz
  sha256: e91e57d8298f3ccf4cce3c5e065bea6eb17033e3c5432b8a22214009c266b2ab

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - branca >=0.3.0
    - jinja2 >=2.9
    - numpy
    - requests

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - folium

about:
  home: https://github.com/python-visualization/folium
  license: MIT
  license_file: LICENSE.txt
  summary: Make beautiful maps with Leaflet.js and Python

extra:
  recipe-maintainers:
    - ocefpaf
    - BibMartin
